___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.zeros(25).reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [5]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [6]:
(np.ones((4,4), dtype=int))*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [7]:
(np.ones((4,4), dtype=int))+6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
my_list1=[7,7,7,7]
np.array([my_list1,my_list1,my_list1,my_list1])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [9]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [10]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [11]:
np.arange(0,25, dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
np.arange(0, 25).reshape(5,5) #5*5=25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [13]:
np.linspace(0,24,25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [14]:
np.random.rand(5)

array([0.51055921, 0.33679188, 0.43275273, 0.9764321 , 0.41487067])

#### 11. Create random normal distributed 5x5 array

In [15]:
np.random.randn(5,5)

array([[-0.29612568,  0.63133034,  0.30597451, -0.15810317, -1.6167426 ],
       [ 0.02903101, -1.0041112 ,  1.8816151 , -1.28564751, -0.11475707],
       [ 0.48618151, -0.16595229, -0.27608508, -1.10524571,  2.15547136],
       [ 0.33123326, -0.79533329,  0.86073546,  0.93345901,  1.52283195],
       [-0.72516254, -0.48476332,  0.77879415,  1.57717463, -0.03603802]])

In [16]:
np.random.rand(5,5)

array([[0.94434898, 0.82978496, 0.77666887, 0.04633554, 0.34206052],
       [0.293187  , 0.82944141, 0.03382018, 0.55271419, 0.03666935],
       [0.68061314, 0.94576016, 0.3507269 , 0.82067573, 0.22004595],
       [0.30019274, 0.17864107, 0.64349863, 0.14396988, 0.39811192],
       [0.63535955, 0.5750748 , 0.69777453, 0.82743965, 0.41389043]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [17]:
np.random.randint(20,50,size=(3,4))

array([[39, 42, 21, 40],
       [44, 29, 40, 28],
       [36, 46, 21, 27]])

#### 13. Reshape the array below with shape 6x8

In [18]:
ranarr

NameError: name 'ranarr' is not defined

In [19]:
np.arange(2,50).reshape(6,8)

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
ranarr = np.random.randint(1,60,48)
ranarr

array([34,  2, 25, 14, 18, 26, 35, 47, 45, 14,  8, 21, 25, 44, 12, 26,  8,
       45, 14, 28, 45, 12, 58, 28, 43, 45, 52, 10, 56,  4,  3, 23, 31, 56,
       16, 26, 49, 34, 59, 30, 21, 32, 46, 49, 46, 59, 46, 27])

In [21]:
ranarr.reshape(6,8)

array([[34,  2, 25, 14, 18, 26, 35, 47],
       [45, 14,  8, 21, 25, 44, 12, 26],
       [ 8, 45, 14, 28, 45, 12, 58, 28],
       [43, 45, 52, 10, 56,  4,  3, 23],
       [31, 56, 16, 26, 49, 34, 59, 30],
       [21, 32, 46, 49, 46, 59, 46, 27]])

In [22]:
##reshape with -1
ranarr.reshape(-1,12)

array([[34,  2, 25, 14, 18, 26, 35, 47, 45, 14,  8, 21],
       [25, 44, 12, 26,  8, 45, 14, 28, 45, 12, 58, 28],
       [43, 45, 52, 10, 56,  4,  3, 23, 31, 56, 16, 26],
       [49, 34, 59, 30, 21, 32, 46, 49, 46, 59, 46, 27]])

In [23]:
ranarr.reshape(6, -1)

array([[34,  2, 25, 14, 18, 26, 35, 47],
       [45, 14,  8, 21, 25, 44, 12, 26],
       [ 8, 45, 14, 28, 45, 12, 58, 28],
       [43, 45, 52, 10, 56,  4,  3, 23],
       [31, 56, 16, 26, 49, 34, 59, 30],
       [21, 32, 46, 49, 46, 59, 46, 27]])

## Numpy Indexing and Selection


In [24]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [25]:
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [26]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [27]:
mat[1, ::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [28]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]]

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
mat[1::2,::2]

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

In [ ]:
mat[mat<10]

In [ ]:
mat[mat>12]

In [ ]:
mat[mat<10]+mat[mat>12]

#### 21. Get the standard deviation of the result above

In [ ]:
(mat[mat<10]+mat[mat>12]).std()

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

In [ ]:
mat[:,2]=[3,7,11,15]

In [ ]:
mat[:,1].sum(axis=0)

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

In [ ]:
mat[2]

In [ ]:
print(f'median {mat[2, :].median()}')

In [ ]:
mat[2, :].mean()

In [ ]:
#median
np.median(mat[2])

In [ ]:
#mean
np.mean(mat[2])

In [ ]:
#std
np.std(mat[2])

# Pandas Section

In [29]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [30]:
sal=pd.read_csv('Salaries.csv')

In [31]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal.info()

In [ ]:
sal.describe()

**How many different year value are there**

In [ ]:
sal.Year.value_counts()

In [ ]:
len(sal['Year'.value_counts()])

**Print out max and avg Totalpay**

In [ ]:
#max
sal.TotalPay.max()

In [ ]:
#avg
sal.TotalPay.mean()

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
sal["TotalPay"][sal.TotalPay > sal.TotalPay.mean()].value_counts()

In [ ]:
len(sal["TotalPay"][sal.TotalPay > sal.TotalPay.mean()].value_counts())

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal["TotalPay"][sal["EmployeeName"]=="ALBERT PARDINI"]

**Who is lowest paid person**

In [ ]:
sal[sal.TotalPayBenefits==sal.TotalPayBenefits.min()]['EmployeeName']

**What are the unique Jobs in dataset?**

In [ ]:
sal.JobTitle.unique()

**List 3 least common Jobs**

In [ ]:
sal["JobTitle"].value_counts().tail(3)

**How many people earned more than avg in 2012**

In [ ]:
sal[(sal.TotalPayBenefits>sal.TotalPayBenefits.mean()) & (sal.Year==2012)]['EmployeeName'].count()

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here
len(sal[sal.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal_new=sal.iloc[:,[0,1,2,7,8]]
sal_new.head()

In [ ]:
sal_new

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
sal_new=sal_new.loc[:,'EmployeeName':'TotalPayBenefits']
sal_new

**Print out the names of the employees who earn more than min, but less than avg**

In [ ]:
sal[(sal.TotalPayBenefits>sal.TotalPayBenefits.min()) & 
       (sal.TotalPayBenefits<sal.TotalPayBenefits.mean())]['EmployeeName']